### ISSUE TITLE
[Improvement] Use mirrors instead of us.archive for apt sources

### ISSUE THREAD

**Issue by Darkless012** [geerlingguy/packer-boxes#32]
Hello, would it be possible to use mirrors for apt sources?

Since apt should support "mirror" URL, I have really large delays when fetching packages from us.archive...

Including link at where I've learned about mirrors: https://askubuntu.com/questions/37753/how-can-i-get-apt-to-use-a-mirror-close-to-me-or-choose-a-faster-mirror

Thank you :)

**Comment by geerlingguy** [comment]
Closing all older issues as I've consolidated all my Packer boxes into this project, and renamed the project. See #45
