### ISSUE TITLE
Add some automated tests

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-boxes#46]
Ideally I'd like CI to run each build... but at least with Travis CI I can't run VirtualBox, so I can't build the VM using Packer and/or test with Vagrant.

Failing that, I'd like to test each build configuration (the Packer JSON), and run Ansible Lint on the Ansible playbook, maybe.

**Comment by mkinney** [comment]
A quick test could leverage `packer validate`. Perhaps something like this: https://github.com/mkinney/packer-boxes/actions

**Comment by geerlingguy** [comment]
@mkinney yeah, that's perfect! I opened a PR from your fork and will merge once the tests complete (adjusted a couple things for style).

**Comment by geerlingguy** [comment]
Thanks again!
