### ISSUE TITLE
Is there a Focal (ubuntu 20.04) ppa for Ansible?

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/packer-boxes#63]
The ubuntu2004/ansible.sh provisioner script is throwing the error
```
E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release' does not have a Release file.
```
https://launchpad.net/~ansible/+archive/ubuntu/ansible-2.9 says there's no focal release for 2.9?

https://launchpad.net/~ansible/+archive/ubuntu/ansible says there's no focal release at all?

**Comment by geerlingguy** [comment]
Please see / follow: https://github.com/ansible/ansible/issues/68645

It seems that there won't be a Focal release for at least some amount of time... I'm currently using `pip3` to install Ansible on 20.04.

**Comment by geerlingguy** [comment]
See also: https://github.com/ansible/ansible/issues/69203

**Comment by basictheprogram** [comment]
Looks like ansible-2.9 is a native package in Focal

https://packages.ubuntu.com/focal/ansible

**Comment by loganmzz** [comment]
As referenced issue is closed to comment, can you please consider updating documentation ? 

cc: ansible/ansible#68645

**Comment by geerlingguy** [comment]
I'm not sure why the issues are closed so unceremoniously for now, but in any case, I don't know where you'd like me to put any documentation? I like installing via Pip.

**Comment by twoatechguy** [comment]
It would be useful to have a PPA for 20.04 now that 19.10 is EOL.

**Comment by geerlingguy** [comment]
This is not the issue to track Ansible's support for 20.04 in their PPA. See PR https://github.com/ansible/ansible/pull/69161

**Comment by gwshepard** [comment]
This simply worked for me https://kifarunix.com/install-and-setup-ansible-on-ubuntu-20-04/

**Comment by bayeslearner** [comment]
Well the lack of the PPA for ansible broke  vagrant ansible_local and  geerlingguy.ansible role  on ubuntu 20.04 if I'm not mistaken.

**Comment by geerlingguy** [comment]
@bayeslearner - I think you might be able to set Vagrant to install via pip instead of packages though, in your Vagrantfile. See the [install_mode](https://www.vagrantup.com/docs/provisioning/ansible_local#install_mode) option.
