### ISSUE TITLE
Include libvirt variants of the boxes.

### ISSUE THREAD

**Issue by 00willo** [geerlingguy/packer-boxes#65]
Thanks for the boxes that you've provided, I've used them a lot.

Would you entertain the idea of including libvirt as an additional provider in addition to virtualbox? If so, I'd be happy to start on a PR to achieve this.

**Comment by geerlingguy** [comment]
@00willo - For my project, for now at least, I'm only maintaining the VirtualBox images. At some point I may change that (I know I entertained the idea of maintaining my own EC2 AMIs as well!), but for now I'm going to stick with just VirtualBox.

**Comment by c-goes** [comment]
I started working on this but found some incompatibilities in dependencies. https://github.com/geerlingguy/ansible-role-packer-debian needs a new release first now that my bugfix is included in master.

**Comment by geerlingguy** [comment]
Sorry about that; new tag is out!
