### ISSUE TITLE
Will you consider have the same but using Hyper-V?

### ISSUE THREAD

**Issue by nmofonseca** [geerlingguy/packer-boxes#66]
Hi Jeff,

I started recently following your work because of the Ansible 101 episodes and I wanted first of all to say great work! and a big Thank you!! When I can I will definitely sponsor you.

Meanwhile I was wondering if you have considered or have any plans to make the boxes available with config for Hyper-V?

Unfortunately on Windows if you have Hyper-V Virtual box can no longer use VT-X.

**Comment by geerlingguy** [comment]
@nmofonseca - At this point, no. I have to limit it to the current set of boxes for maintainability. I used to maintain VMware compatibility too, and was considering EC2 AMIs, but the amount of work was a little more than I was willing to take on.

Note that VirtualBox should be able to work with Hyper-V now, see [Use VirtualBox and Hyper-V at the same time thanks to the Hyper-V API](https://us.informatiweb.net/tutorials/it/virtualization/virtualbox-use-virtualbox-and-hyper-v-at-the-same-time.html).

**Comment by nmofonseca** [comment]
Hello @geerlingguy , thank you anyway for taking the time to reply I know you are a busy guy.  A big tank you also for the link you sent unfortunately I can't use it since I don't have the right Windows 10 version, however I will try this [workaround ]https://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx(url)
