### ISSUE TITLE
Packer-1.6.0 throws error Deprecated configuration key: 'iso_checksum_type'

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/packer-boxes#68]
```
$ packer build -var 'version=1.2.0' box-config.json
Error: Failed to prepare build: "virtualbox-iso"

1 error occurred:
	* Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.
```
```
$ packer --version
1.6.0
```
```
Ubuntu 20.04 LTS
```

**Comment by geerlingguy** [comment]
Commit where this was introduced: https://github.com/hashicorp/packer/commit/0fa60c68fbfcf5ef29485489a41f5afa0565bdee

**Comment by sevenday4** [comment]
1 error occurred:
	* Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
packer --version
1.6.6
I have tried packer fix old.json > new.json to no avail. I am running on Linux. I have even with -validte=false and still no joy.
