### ISSUE TITLE
centos/7 with gui doesn't resize properly.

### ISSUE THREAD

**Issue by queglay** [geerlingguy/packer-boxes#74]
Thankyou for your work on this project!

I found that when I use the centos/7 box (updated to try try this today), that if I try and setup a gui the window wont resize much larger.  If I resize the window to twice the size, the display becomes black.

The gui for Centos 7 can be configured with:
```
    config.vm.provision "shell", inline: "sudo yum groupinstall -y 'gnome desktop'"
    config.vm.provision "shell", inline: "sudo yum install -y 'xorg*'"
    config.vm.provision "shell", inline: "sudo yum remove -y initial-setup initial-setup-gui"
    config.vm.provision "shell", inline: "sudo systemctl isolate graphical.target"
    config.vm.provision "shell", inline: "sudo systemctl set-default graphical.target"
    config.vm.provision "shell", inline: "sudo yum install -y python3"
```

I am running this on a Centos 7 host with NVIDIA P5000 Graphics driver version v440.44

When I run this same set of commands with the box named "centos/7" instead (not "geerlingguy/centos7"), it works.

**Comment by geerlingguy** [comment]
@queglay - Thanks for filing the issue! Unfortunately, I do not intend for these boxes to be used with a GUI as they are mainly used for headless testing and server builds. Thanks for posting the details of how you got the GUI working; maybe consider forking this project or breaking out the CentOS box configuration into a separate repository and you can work on getting the GUI bits working correctly there?

**Comment by queglay** [comment]
No worries Jeff, thanks for your response. I've not used Packer yet but perhaps it's time.
