### ISSUE TITLE
Use Unicode locale?

### ISSUE THREAD

**Issue by isido** [geerlingguy/packer-boxes#8]
Hello,

thanks for nice packer files, they saved some work for me! Is there any reason for not using an uncode locale (eg. `en_US.UTF-8`)?

**Comment by geerlingguy** [comment]
For the locale default, I'm just setting what is commonly seen in docs as a default for US localization; see:

  - https://www.debian.org/releases/stable/amd64/apbs04.html.en
  - https://github.com/geerlingguy/packer-ubuntu-1604/blob/master/http/preseed.cfg#L30

I originally pulled the base for this project out of Chef's Bento project, which uses: https://github.com/chef/bento/blob/0200704bfc43c9873abcbe243ca6e328812441e1/ubuntu/ubuntu-16.04-i386.json#L15 (originally it was just en_US).

I'd be willing to accept a PR to add the UTF-8 setting.

**Comment by geerlingguy** [comment]
Closing all older issues as I've consolidated all my Packer boxes into this project, and renamed the project. See #45
