### ISSUE TITLE
AlmaLinux/RockyLinux Support

### ISSUE THREAD

**Issue by ashleykleynhans** [geerlingguy/packer-boxes#80]
Thanks for another awesome project as always!

Any chance you can add support for an AlmaLinux box due to the issues with CentOS 8?

**Comment by geerlingguy** [comment]
I'm a bit more on the RockyLinux side, but I've been waiting for that to hit a stable release before deciding what to do next.

I will likely be dropping support for CentOS 8 pretty much everywhere over the next six months to a year, but in whatever way takes the least amount of effort :D

**Comment by ashleykleynhans** [comment]
Thanks, now that RockyLinux is out, any plans to add support for it?

**Comment by geerlingguy** [comment]
Yes, possibly. Haven't had time to dig into it, and right now since I'm on M1 Macs, it's a lower priority for me, personally, since making the box wouldn't help (at least in VirtualBox-land).

**Comment by jonathanspw** [comment]
Alma has a bit higher adoption so far.

**Comment by geerlingguy** [comment]
Planning on adding a rockylinux8 box now... testing a build: https://app.vagrantup.com/geerlingguy/boxes/rockylinux8
